### ISSUE TITLE
About the types of edges in DHGN

### ISSUE THREAD

**Issue by krystalan** [xcfcode/DHGN#3]
Thanks for your remarkable work!

In your paper, Sec. 2.4, there are **four** types of edges that exist in the Heterogeneous Dialogue Graph: speak-by, know-by, rev-speak-by and rev-know-by.
And I also find there are **three** types of edges in the code (data/*.edge_types.txt). I also read the data/*.edge_index.txt file, and I guess the "speak-by" edge is not present.

I don't know if I understand it wrong. I sincerely hope you can answer it.

**Comment by xcfcode** [comment]
Sorry for the unclarity. This is indeed a mismatch between the paper and this code. Since I find that the utterance information is not useful for speaker representation, so there are only three types of edges:  `speak-by, know-by and rev-know-by`.

**Comment by krystalan** [comment]
Thanks a lot!
