### ISSUE TITLE
请问一下test.edge_index.txt

### ISSUE THREAD

**Issue by Sperao** [xcfcode/DHGN#4]
![image](https://user-images.githubusercontent.com/65717274/136926383-42378e2c-25a9-4fae-ad43-d0d56f2ef524.png)

**Comment by Sperao** [comment]
请问一下这三个文件数据是如何处理得到的呢，数据的意思又是啥

**Comment by xcfcode** [comment]
- `node_type`: 节点类型
- `edge_type`：边类型
- `edge_index`: 两个节点之间存在边
